# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v

  docker-build:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - uses: actions/checkout@v3
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/demo:latest,${{ secrets.DOCKER_USER }}/demo:${{ steps.vars.outputs.sha_short }}
          
    
